#!/bin/bash
#Bogatyrev Ilya
#ilia.bogatyrev@gmail.com
#Проверяю, есть ли параметр(файл)
#Если есть, присваиваю имя файла переменной
#Если нет, то считаю файл со стандартного потока ввода
#Необходимо доработать ввод со стандартного потока(6-14 строки)
if [ $# -eq 1 ]
then
file=$1
else
echo "incorrect parameter"
echo "exit"
exit
fi
echo "$1"
#Создаю директорию для временных файлов
#Вывожу файл в битовом представлении по октетам
xxd -b $1 |
#Фильтрую вывод xxd - убираю адресные сдвиги и окончания, только октеты в строках оставляю
sed 's/^.\{10\}//g' |
sed 's/.\{8\}$//g' |
#grep элементов подходящих под регулярку по октету в строке сохраняю во временный файл OctetInMultStrings
grep -o '[0-1]\{8\}' >> octetsInMultStrings
#Пробегаю по строкам файла, отправляю все в файл без переноса на новую строку
#Формируется файл с октетами в одну линию
while read octet
do
  echo -n "$octet " 1>>oneLineFile
done < octetsInMultStrings
rm octetsInMultStrings
echo "octetsInOneLine:"
cat oneLineFile
echo
