#!/bin/bash
#Bogatyrev Ilya
#ilia.bogatyrev@gmail.com
#Проверяем, есть ли параметр(файл)
#Если есть, присваиваем имя файла, переменной
#Если нет, то считаем файл со стандартного потока ввода
#Необходимо доработать ввод со стандартного потока(6-14 строки)
if [ $# -eq 1 ]
then
file=$1
else
echo "incorrect parameter"
echo "exit"
exit
fi
echo "$1"
#Создаю директорию для временных файлов
#Вывожу файл в битовом представлении по октетам
xxd -b $1 1>xxdoutput

#Фильтрую вывод xxd - убираю заголовки строк и окончания, только октеты в строках оставляю
cat xxdoutput |
sed 's/^.\{10\}//g' |
sed 's/.\{8\}$//g' >> xxdMultStrings
#Удаляем временные файлы
rm xxdoutput
echo "xxdMultStrings:"
cat xxdMultStrings
echo "grepped:"
#grep элементов подходящих под регулярку по октету в строке сохраняем во временный файл OctetInMultStrings
cat xxdMultStrings |
grep -o '[0-1]\{8\}' >> octetsInMultStrings
rm xxdMultStrings

#Файл с октетами в одну линию
while read octet
do
  echo -n "$octet " 1>>oneLineFile
done < octetsInMultStrings
rm octetsInMultStrings
#Удаляю временные файлы
echo "oneLineFile:"
cat oneLineFile



#echo "$xxdMultStrings";

#Ниже мусор
#currentDir=$(pwd);
#echo $currentDir;
#bitview=$(xxd -b $currentDir/$1);
#echo "$hexview";
